name: Build package in Docker
description: Build package in Docker
inputs:
  reposlug:
    description: GitHub build repository slug
    required: true
  release:
    description: Tag name for repository release
    required: true
  runid:
    description: Run ID number
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{inputs.reposlug}}
    - ${{inputs.release}}
    - ${{inputs.runid}}
