language: generic
dist: xenial
before_install:
  - bash prepare.sh
script:
  - bash updrepo.sh $TRAVIS_REPO_SLUG
before_deploy:
  - cp -a repo $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ${TRAVIS_TAG}/*.{db,files,gz,xz,sig}
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true
