name: Update database files
description: Update database files
inputs:
  repo_token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
    - run: ${{github.action_path}}/action.sh ${{github.token}}
      shell: bash
