name: Update repository index

env:
  REPO_NAME: PKGBUILD
  RELEASE_NAME: repository
  KEY_FILE: signing.key.enc

on:
  # Run when repository files are updated
  push:
    paths:
      - 'files/**'
  # Allow manual trigger as well
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  updrepo:
    name: Update repository index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: ./.github/actions/updrepo

      - uses: ./.github/actions/signrepo
        with:
          key: ${{secrets.key}}
          iv: ${{secrets.iv}}
          signingkey: ${{env.KEY_FILE}}
        continue-on-error: true

      - uses: actions/github-script@v3.1.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const rel = await github.repos.getReleaseByTag({owner: 'djpohly', repo: 'PKGBUILD', tag: 'repository'})
            console.log(rel)

      - uses: svenstaro/upload-release-action@2.2.0
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.RELEASE_NAME}}
          file: 'repo/*'
          file_glob: true
          overwrite: true
